services:

  #
  # CrawlSharp
  # See https://hub.docker.com/r/jchristn/crawlsharp
  # and https://github.com/jchristn/crawlsharp
  #

  crawlsharp:
    container_name: 'crawlsharp'
    image: 'jchristn/crawlsharp:v1.0.0'
    network_mode: 'host'
    stdin_open: true
    tty: true
    healthcheck:
      test: curl --fail http://localhost:8000
